#!/bin/bash
#PBS -V


cp  /home/cnieverg/gctam/grm/pruned_alldata_norel_males.* "$TMPDIR"/.

cd "$TMPDIR"
/home/cnieverg/gctam/bolt --bfile pruned_alldata_norel_males --phenoFile /home/cnieverg/gctam/ss_fixed.pheno2.txt --phenoCol Pheno_fix  --reml --remlNoRefine > /home/cnieverg/gctam/boltres/boltmodel_fastreml_norel_newpheno_cov_males.txt




#--covarFile /home/cnieverg/gctam/ss_fixed.pheno2.txt --covarCol Study