#!/bin/bash
#PBS -V

while getopts w: option
do
  case "${option}"
    in
      w) working_dir=${OPTARG};;
    esac
done

plinkl=/home/cnieverg/gctam/plink
chr="$PBS_ARRAYID"
mkdir "$TMPDIR"/gct
sname=alldata

   ls /home/cnieverg/gctam/bychr | grep b"$chr"\.bed | sed 's/.bed//g'  | awk '{print $1".bed",$1".bim",$1".fam"}' > "$TMPDIR"/gct/alldata_"$chr".mergelist
   for files in $(ls /home/cnieverg/gctam/bychr | grep   -F b"$chr"\. ) 
   do
    cp /home/cnieverg/gctam/bychr/"$files" "$TMPDIR"/gct/.
   done

   cp "$TMPDIR"/gct/alldata_"$chr".mergelist "$working_dir"/.

   cd  "$TMPDIR"/gct

   #$plinkl --maf 0.01 --geno 0.02  --allow-no-sex --merge-list "$TMPDIR"/gct/alldata_"$chr".mergelist  --make-grm-bin --out "$working_dir"/"$sname"_m"$chr" &>  "$working_dir"/"$sname"_m"$chr".mlog  

   $plinkl --maf 0.01 --geno 0.02  --allow-no-sex --merge-list "$TMPDIR"/gct/alldata_"$chr".mergelist  --make-bed --out "$working_dir"/"$sname"_b"$chr" &>  "$working_dir"/"$sname"_b"$chr".mlog  




#working_dir=/home/cnieverg/gctam/grm
#for chr in {1..21} # 22 # {1..22}
#do
# ls /home/cnieverg/gctam/bychr | grep b"$chr"\.bed | sed 's/.bed//g'  | awk '{print $1".bed",$1".bim",$1".fam"}' > "$working_dir"/blackalldata_"$chr".mergelist

# $plinkl --maf 0.01 --geno 0.02  --allow-no-sex --merge-list "$working_dir"/blackalldata_"$chr".mergelist  --make-bed --out "$working_dir"/"$sname"_b"$chr" # &>  "$working_dir"/"$sname"_b"$chr".mlog  
#done